/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import com.mysql.jdbc.Statement;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Abimael
 */
public class NewCatalogo extends javax.swing.JPanel {

    private BD.ConexionBD con = new BD.ConexionBD();

    /**
     * Creates new form NewCatalogo
     */
    public NewCatalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jbPaquete1 = new javax.swing.JButton();
        lblPaquete1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPaquete2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbPaquete2 = new javax.swing.JButton();

        jFileChooser1.setDialogTitle("Seleccione imagen del catalogo");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setToolTipText("");

        jbPaquete1.setBackground(null);
        jbPaquete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addMin.png"))); // NOI18N
        jbPaquete1.setBorder(null);
        jbPaquete1.setBorderPainted(false);
        jbPaquete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPaquete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPaquete1ActionPerformed(evt);
            }
        });

        lblPaquete1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        lblPaquete1.setText("Agregar nueva imagen");
        lblPaquete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setText(" Para agregar una nueva imagen presiona el boton con el simbolo +.");

        lblPaquete2.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        lblPaquete2.setText("Nombre:");
        lblPaquete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText(" Para guardar los cambios presiona el icono con el disquete.");

        jLabel3.setText(" Si la imagen seleccionada no es la deseada, haz click de nuevo en la imagen.");

        jbPaquete2.setBackground(new java.awt.Color(255, 255, 255));
        jbPaquete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/question.png"))); // NOI18N
        jbPaquete2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbPaquete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPaquete1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPaquete1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPaquete2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPaquete2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaquete2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPaquete1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPaquete1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jbPaquete2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    File selectedFile=null;
    private void jbPaquete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPaquete1ActionPerformed
        // TODO add your handling code here:
        int status = jFileChooser1.showOpenDialog(null);
        if (status == JFileChooser.APPROVE_OPTION) {
            selectedFile = jFileChooser1.getSelectedFile();
            //jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
            jbPaquete2.setIcon(new javax.swing.ImageIcon(selectedFile.getPath())); // NOI18N
        }
    }//GEN-LAST:event_jbPaquete1ActionPerformed
    private boolean validaCatalogo() {
        boolean retorno = true;
        if (jTextField1.getText().trim().length() == 0) {
            retorno = false;
        }else if (selectedFile == null) {
            retorno = false;
        }
        return retorno;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:implementar esta accion
        if (validaCatalogo()) {
            InputStream in = null;
            OutputStream ou = null;
            try {
                File oldImagen = new File(selectedFile.getPath());
                File newImagen = new File("src/Imagenes/Catalogo" + selectedFile.getName());
                in = new FileInputStream(oldImagen);
                ou = new FileOutputStream(newImagen);
                byte[] moveBuff = new byte[1024];
                int butesRead;
                while ((butesRead = in.read(moveBuff)) > 0) {
                    ou.write(moveBuff, 0, butesRead);
                }
                in.close();
                ou.close();
                java.sql.Connection jsc = con.conectar();
                if (jsc != null) {
                    try {
                        Statement st;
                        st = (Statement) jsc.createStatement();
                        if (st.executeUpdate("insert into catalogo(descripcion,imagen) values ('"
                                + jTextField1.getText()
                                + "','/Imagenes/Catalogo"
                                + selectedFile.getName() + "') ") != 0) {
                            JOptionPane.showMessageDialog(this, "El nuevo Catalogo se creó con exito.");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ModificarSistema.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Conexion fallida");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Es necesario seleccionar una imagen y un nombre.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbPaquete1;
    private javax.swing.JButton jbPaquete2;
    private javax.swing.JLabel lblPaquete1;
    private javax.swing.JLabel lblPaquete2;
    // End of variables declaration//GEN-END:variables
}
