
package aplicacion;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.Calendar;
import javax.swing.JFrame;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Maria
 */
public class VerReportes extends javax.swing.JPanel {

    /**
     * Creates new form VerReportes
     */
    JFreeChart grafica;
    DefaultCategoryDataset datos= new DefaultCategoryDataset();
    
    public VerReportes() {
        initComponents();
        initComponentsByUser();
    }
    private void initComponentsByUser(){
        bgFiltros.add(jrbPorDia);
        bgFiltros.add(jrbPorSemana);
        bgFiltros.add(jrbPorMes);
        bgFiltros.add(jrbPorAño);
        setWeeksofMonth();
    }
    private void setWeeksofMonth(){
        java.util.Calendar cal= java.util.Calendar.getInstance();
        cal.set(Calendar.YEAR, jycElegirAñoSemana.getYear());
        cal.set(Calendar.MONTH, jmcElegirMesSemana.getMonth());
        cal.set(Calendar.DAY_OF_MONTH,1);
        if(jspNumeroSemana.getValue() > cal.getActualMaximum(Calendar.WEEK_OF_MONTH)){
            jspNumeroSemana.setValue(cal.getActualMaximum(Calendar.WEEK_OF_MONTH));
        }
        jspNumeroSemana.setMaximum(cal.getActualMaximum(Calendar.WEEK_OF_MONTH));
    }
    private void graficar(){
        datos.addValue(1, "Negocio 1", "Lunes");
        datos.addValue(2, "Negocio 1", "Martes");
        datos.addValue(3, "Negocio 1", "Miercoles");
        datos.addValue(1, "Negocio 1", "Jueves");
        datos.addValue(5, "Negocio 1", "Viernes");
        datos.addValue(6, "Negocio 1", "Sabado");
        datos.addValue(1, "Negocio 1", "Domingo");
        grafica=ChartFactory.createBarChart("Vista Ejemplo", "dias", "visitas", datos, PlotOrientation.VERTICAL,true,true,false );
        ChartPanel panelAux=new ChartPanel(grafica);
        jPanelDatosGraf.removeAll();
        //jPanelDatosGraf.setLayout(new FlowLayout(FlowLayout.TRAILING));
        //jPanelDatosGraf.add(panelAux);
        
        //solo aqui metiendo mi cucharota jejeje solo remplaze las lineas de abjajo por las de arriba  
        
        jPanelDatosGraf.add(panelAux,BorderLayout.CENTER);
        jPanelDatosGraf.validate();
        
        
//        JFrame fram=new JFrame("Grafica");
//        fram.getContentPane().add(panelAux);
//        fram.pack();
//        fram.setVisible(true);
//        fram.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltros = new javax.swing.ButtonGroup();
        tituloReportes = new javax.swing.JLabel();
        jrbPorDia = new javax.swing.JRadioButton();
        jrbPorSemana = new javax.swing.JRadioButton();
        jrbPorMes = new javax.swing.JRadioButton();
        jrbPorAño = new javax.swing.JRadioButton();
        lblImagen = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jdcElegirDia = new com.toedter.calendar.JDateChooser();
        jmcElegirMes = new com.toedter.calendar.JMonthChooser();
        jycElegirAño = new com.toedter.calendar.JYearChooser();
        jycElegirAñoSemana = new com.toedter.calendar.JYearChooser();
        jmcElegirMesSemana = new com.toedter.calendar.JMonthChooser();
        jspNumeroSemana = new com.toedter.components.JSpinField();
        jycElegirAñoMes = new com.toedter.calendar.JYearChooser();
        jsPanelGraficas = new javax.swing.JScrollPane();
        jPanelGraficas = new javax.swing.JPanel();
        lblTituloPedidos = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jPanelDatosGraf = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        tituloReportes.setBackground(new java.awt.Color(51, 51, 255));
        tituloReportes.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        tituloReportes.setForeground(new java.awt.Color(204, 255, 204));
        tituloReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloReportes.setText("Reportes de Ventas");
        tituloReportes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tituloReportes.setOpaque(true);

        jrbPorDia.setBackground(new java.awt.Color(255, 255, 255));
        jrbPorDia.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jrbPorDia.setSelected(true);
        jrbPorDia.setActionCommand("porDia");
        jrbPorDia.setLabel("Por día");
        jrbPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorDiaActionPerformed(evt);
            }
        });

        jrbPorSemana.setBackground(new java.awt.Color(255, 255, 255));
        jrbPorSemana.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jrbPorSemana.setText("Por semana");
        jrbPorSemana.setActionCommand("porSemana");
        jrbPorSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorSemanaActionPerformed(evt);
            }
        });

        jrbPorMes.setBackground(new java.awt.Color(255, 255, 255));
        jrbPorMes.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jrbPorMes.setText("Por mes");
        jrbPorMes.setActionCommand("porMes");
        jrbPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorMesActionPerformed(evt);
            }
        });

        jrbPorAño.setBackground(new java.awt.Color(255, 255, 255));
        jrbPorAño.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jrbPorAño.setText("Por Año");
        jrbPorAño.setActionCommand("porAnio");
        jrbPorAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorAñoActionPerformed(evt);
            }
        });

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grafCirculo.jpg"))); // NOI18N
        lblImagen.setToolTipText("");

        lblSubtitulo.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        lblSubtitulo.setText("Selecciona el periodo que deseas consultar.");

        jdcElegirDia.setDate(new java.util.Date());
        jdcElegirDia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcElegirDiaPropertyChange(evt);
            }
        });

        jmcElegirMes.setEnabled(false);
        jmcElegirMes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jmcElegirMesPropertyChange(evt);
            }
        });

        jycElegirAño.setEnabled(false);
        jycElegirAño.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jycElegirAñoPropertyChange(evt);
            }
        });

        jycElegirAñoSemana.setEnabled(false);
        jycElegirAñoSemana.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jycElegirAñoSemanaPropertyChange(evt);
            }
        });

        jmcElegirMesSemana.setEnabled(false);
        jmcElegirMesSemana.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jmcElegirMesSemanaPropertyChange(evt);
            }
        });

        jspNumeroSemana.setEnabled(false);
        jspNumeroSemana.setMaximum(10);
        jspNumeroSemana.setMinimum(1);
        jspNumeroSemana.setValue(1);
        jspNumeroSemana.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jspNumeroSemanaPropertyChange(evt);
            }
        });

        jycElegirAñoMes.setEnabled(false);
        jycElegirAñoMes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jycElegirAñoMesPropertyChange(evt);
            }
        });

        jsPanelGraficas.setBackground(new java.awt.Color(255, 255, 255));
        jsPanelGraficas.setBorder(null);

        jPanelGraficas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGraficas.setPreferredSize(new java.awt.Dimension(829, 350));

        lblTituloPedidos.setBackground(new java.awt.Color(51, 51, 255));
        lblTituloPedidos.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        lblTituloPedidos.setForeground(new java.awt.Color(204, 255, 204));
        lblTituloPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPedidos.setText("Pedidos realizados en el periodo");
        lblTituloPedidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        lblTituloPedidos.setOpaque(true);

        jPanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelDatos.setPreferredSize(new java.awt.Dimension(403, 2));

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        jPanelDatosGraf.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatosGraf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelDatosGraf.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelGraficasLayout = new javax.swing.GroupLayout(jPanelGraficas);
        jPanelGraficas.setLayout(jPanelGraficasLayout);
        jPanelGraficasLayout.setHorizontalGroup(
            jPanelGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGraficasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelGraficasLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lblTituloPedidos)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanelGraficasLayout.setVerticalGroup(
            jPanelGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGraficasLayout.createSequentialGroup()
                .addComponent(lblTituloPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatosGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addContainerGap())
        );

        jsPanelGraficas.setViewportView(jPanelGraficas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblSubtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbPorDia)
                            .addComponent(jrbPorMes)
                            .addComponent(jrbPorAño)
                            .addComponent(jrbPorSemana))
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jdcElegirDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jycElegirAñoSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jmcElegirMesSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jspNumeroSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jycElegirAñoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jmcElegirMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jycElegirAño, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tituloReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addComponent(jsPanelGraficas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jycElegirAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSubtitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jrbPorDia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbPorSemana)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbPorMes))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jdcElegirDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jycElegirAñoSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jmcElegirMesSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jspNumeroSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jmcElegirMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jycElegirAñoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)))
                                .addComponent(jrbPorAño))
                            .addComponent(lblImagen))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsPanelGraficas, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPorSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorSemanaActionPerformed
        // TODO add your handling code here:
        jdcElegirDia.setEnabled(false);
        jycElegirAñoSemana.setEnabled(true);
        jmcElegirMesSemana.setEnabled(true);
        jspNumeroSemana.setEnabled(true);
        jmcElegirMes.setEnabled(false);
        jycElegirAñoMes.setEnabled(false);
        jycElegirAño.setEnabled(false);
        
    }//GEN-LAST:event_jrbPorSemanaActionPerformed

    private void jrbPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorDiaActionPerformed
        // TODO add your handling code here:
        jdcElegirDia.setEnabled(true);
        jycElegirAñoSemana.setEnabled(false);
        jmcElegirMesSemana.setEnabled(false);
        jspNumeroSemana.setEnabled(false);
        jmcElegirMes.setEnabled(false);
        jycElegirAñoMes.setEnabled(false);
        jycElegirAño.setEnabled(false);
    }//GEN-LAST:event_jrbPorDiaActionPerformed

    private void jrbPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorMesActionPerformed
        // TODO add your handling code here:
        jdcElegirDia.setEnabled(false);
        jycElegirAñoSemana.setEnabled(false);
        jmcElegirMesSemana.setEnabled(false);
        jspNumeroSemana.setEnabled(false);
        jmcElegirMes.setEnabled(true);
        jycElegirAñoMes.setEnabled(true);
        jycElegirAño.setEnabled(false);
    }//GEN-LAST:event_jrbPorMesActionPerformed

    private void jrbPorAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorAñoActionPerformed
        // TODO add your handling code here:
        jdcElegirDia.setEnabled(false);
        jycElegirAñoSemana.setEnabled(false);
        jmcElegirMesSemana.setEnabled(false);
        jspNumeroSemana.setEnabled(false);
        jmcElegirMes.setEnabled(false);
        jycElegirAñoMes.setEnabled(false);
        jycElegirAño.setEnabled(true);
    }//GEN-LAST:event_jrbPorAñoActionPerformed

    private void jycElegirAñoSemanaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jycElegirAñoSemanaPropertyChange
        // TODO add your handling code here:
        setWeeksofMonth();
        graficar();
    }//GEN-LAST:event_jycElegirAñoSemanaPropertyChange

    private void jmcElegirMesSemanaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmcElegirMesSemanaPropertyChange
        // TODO add your handling code here:
        setWeeksofMonth();
        graficar();
    }//GEN-LAST:event_jmcElegirMesSemanaPropertyChange

    private void jdcElegirDiaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcElegirDiaPropertyChange
        // TODO add your handling code here:
        graficar();
    }//GEN-LAST:event_jdcElegirDiaPropertyChange

    private void jspNumeroSemanaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jspNumeroSemanaPropertyChange
        // TODO add your handling code here:
        graficar();
    }//GEN-LAST:event_jspNumeroSemanaPropertyChange

    private void jycElegirAñoMesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jycElegirAñoMesPropertyChange
        // TODO add your handling code here:
        graficar();
    }//GEN-LAST:event_jycElegirAñoMesPropertyChange

    private void jmcElegirMesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmcElegirMesPropertyChange
        // TODO add your handling code here:
        graficar();
    }//GEN-LAST:event_jmcElegirMesPropertyChange

    private void jycElegirAñoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jycElegirAñoPropertyChange
        // TODO add your handling code here:
        graficar();
    }//GEN-LAST:event_jycElegirAñoPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltros;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatosGraf;
    private javax.swing.JPanel jPanelGraficas;
    private com.toedter.calendar.JDateChooser jdcElegirDia;
    private com.toedter.calendar.JMonthChooser jmcElegirMes;
    private com.toedter.calendar.JMonthChooser jmcElegirMesSemana;
    private javax.swing.JRadioButton jrbPorAño;
    private javax.swing.JRadioButton jrbPorDia;
    private javax.swing.JRadioButton jrbPorMes;
    private javax.swing.JRadioButton jrbPorSemana;
    private javax.swing.JScrollPane jsPanelGraficas;
    private com.toedter.components.JSpinField jspNumeroSemana;
    private com.toedter.calendar.JYearChooser jycElegirAño;
    private com.toedter.calendar.JYearChooser jycElegirAñoMes;
    private com.toedter.calendar.JYearChooser jycElegirAñoSemana;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloPedidos;
    private javax.swing.JLabel tituloReportes;
    // End of variables declaration//GEN-END:variables
}
